services:
  api:
    environment:
      - PORT=${PORT:-8000}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE=${LOG_FILE:-logs/app.log}
    # docker image from dockerhub
    image: ${IMAGE}
    # local build, uncomment if you want to create your image locally
    # build: .
    container_name: heart_api
    ports:
      - "${PORT:-8000}:8000"
    # model artifacts
    volumes:
      - ./artifacts:/app/artifacts
      - ./logs:/app/logs
    restart: unless-stopped
