line-length = 100
target-version = "py312"

[lint]
select = ["E", "F", "I"]       # base errors
ignore = []                    # codes for ignore

[format]
quote-style = "double"
indent-style = "space"
